### ISSUE TITLE
heads up - login/out in devpi-web

### ISSUE THREAD

**Issue by fschulze** [saxix/devpi-theme-16#1]
We plan to add login/out views to devpi-web in the future. Basically [devpi-lockdown](https://pypi.org/project/devpi-lockdown/) will be merged into it. This will cause a route conflict. You can see that by installing devpi-lockdown together with devpi-theme-16. I guess you should do the same you did for the login route and create a non conflicting one. We don't have a timetable for that change yet though.

**Comment by saxix** [comment]
@fschulze  thx for the infos.  Looking at `devpi-lockdown` I'm thinking to use it directly and remove login/logout custom views from the theme. Do you see any impediments about that ?

**Comment by fschulze** [comment]
That should work as well. I think pluggy then allows us to just disable devpi-lockdown once it's in devpi-web

**Comment by fschulze** [comment]
Looks like you released this with 2.1.0.
